---
  - name: Installs dependencies
    tags: docker
    apt: name={{item}} state=installed update_cache=true
    with_items:
      - apt-transport-https
      - ca-certificates

  - name: Adds apt key 
    tags: docker
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

  - name: Adds apt repository
    tags: docker
    apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

  - name: Absent state for lxc-docker pkg
    tags: docker
    apt: pkg=lxc-docker state=absent

  - name: Installs docker
    tags: docker
    apt: pkg=docker-engine state=installed update_cache=false

  - name: Adds docker group
    tags: docker
    group: name=docker state=present

  - name: Adds system user to docker group
    tags: docker
    user: name="{{system_user}}" shell=/bin/bash groups=docker append=yes
